pipeline {
    agent any
    environment {
        SUDO_PASSWORD=credentials('root-credential')
        JENKINS_PASSWORD=credentials('jenkins-user-credential')
    }
    stages {
        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }
        stage('Add Execute Permission') {
            steps {
                sh 'chmod +x jenkins/scripts/test.sh'
                sh 'chmod +x jenkins/scripts/build.sh'
                sh 'chmod +x jenkins/scripts/deliver.sh'
            }
        }
        stage('Test') { 
            steps {
                sh 'jenkins/scripts/test.sh'
            }
        }
        stage('Build') {
            steps {
                sh 'jenkins/scripts/build.sh'
            }
        }
        stage('Deliver') {
            steps {
              sh 'jenkins/scripts/deliver.sh'
              input message: 'Finished using the web site? (Click "Proceed" to continue)'
            }
        }
    }
}