pipeline {
    agent any
    stages {
        stage('Install Dependencies') { 
            steps {
                sh 'npm install'
            }
        }
        stage('Test') { 
            steps {
                sh 'jenkins/scripts/test.sh'
            }
        }
        stage('Build') {
            steps {
                sh 'jenkins/scripts/build.sh'
            }
        }
        stage('Deliver') {
            steps {
              sh 'jenkins/scripts/deliver.sh'
              input message: 'Finished using the web site? (Click "Proceed" to continue)'
            }
        }
    }
}